version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    #uncomment following lines to access db locally
    ports:
      - 27017:27017
    networks: 
     - network-backend
     
  portainer:
     image: portainer/portainer-ce
     ports:
      - "9000:9000"
     networks:
      - network-backend
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - network-backend
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - network-backend
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro
      
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    ports:
      - "8080:8080"
    networks:
      - network-backend
    volumes:
      - /:/host:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3002"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - network-backend
    volumes:
      - grafana_data:/var/lib/grafana
    dependson:
      - web 

networks:
  network-backend:

volumes:
  mongodb_data:
  portainer_data:
  grafana_data:


 

